/**
 * F8-26 — EmailLayout: shared email layout component
 *
 * Per PAD §16.2:
 * - Single-column, 600px max width
 * - Safe hex colors (NOT CSS variables — email clients don't support them)
 * - CAN-SPAM + GDPR compliant footer (studio address + unsubscribe link)
 * - System serif stack with Cormorant fallback
 * - Plain text version auto-generated by React Email
 *
 * Per ADR-010: This component is used for LOCAL JSX rendering only
 * (Next.js Server Components). Trigger.dev workers use Resend Native
 * Templates — they do NOT import this component at runtime.
 *
 * Source: MEP F8-26, PAD §16.2.
 */

import { Html, Head, Preview, Body, Container, Section, Text } from 'react-email';
import type { ReactNode } from 'react';
import { EmailFooter } from './EmailFooter';

// Safe hex colors from the Stillwater token set (PAD §11.3)
// These are hardcoded because email clients don't support CSS variables
const COLORS = {
  stone900: '#1C1915',
  stone700: '#3D3832',
  stone400: '#8C7B6E',
  sand: '#F5F0E8',
  sandWarm: '#EDE5D8',
  clay400: '#C4856A',
  clay500: '#9E5E44',
  water500: '#7B9EA8',
} as const;

export interface EmailLayoutProps {
  children: ReactNode;
  /** Preview text shown in email client inbox preview (50-100 chars) */
  previewText?: string;
}

export function EmailLayout({ children, previewText }: EmailLayoutProps) {
  return (
    <Html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>{`
          body { margin: 0; padding: 0; background-color: ${COLORS.sand}; }
          table { border-collapse: collapse; }
          img { border: 0; outline: none; text-decoration: none; }
          a { color: ${COLORS.clay500}; text-decoration: underline; }
        `}</style>
      </Head>
      <Preview>{previewText ?? ''}</Preview>
      <Body style={bodyStyle}>
        <Container width={600} style={containerStyle}>
          <Section style={contentStyle}>
            {children}
          </Section>
          <EmailFooter />
        </Container>
      </Body>
    </Html>
  );
}

const bodyStyle: React.CSSProperties = {
  backgroundColor: COLORS.sand,
  fontFamily: 'Georgia, "Times New Roman", serif',
  margin: 0,
  padding: 0,
};

const containerStyle: React.CSSProperties = {
  backgroundColor: COLORS.sandWarm,
  maxWidth: '600px',
  margin: '0 auto',
  padding: '32px 24px',
};

const contentStyle: React.CSSProperties = {
  color: COLORS.stone900,
  fontSize: '16px',
  lineHeight: '1.65',
};
