/**
 * Stillwater — ESLint v9 Flat Config Entry Point (apps/web)
 *
 * ESLint v9 requires a local eslint.config.{js,mjs,cjs} file in the
 * project root. This file imports the shared Stillwater ESLint config
 * from @stillwater/eslint-config (tooling/eslint/index.js).
 *
 * The shared config includes: TypeScript strict, React 19, Next.js 16,
 * Tailwind CSS v4, Import order, and Tailwind class validation rules.
 */

import sharedConfig from '@stillwater/eslint-config';

export default [
  ...sharedConfig,
  {
    // shadcn/ui components are generated by `npx shadcn add` and use
    // React.forwardRef (deprecated in React 19 but still works) + ElementRef
    // (deprecated, replaced by ComponentRef). These are third-party-generated
    // files; lint issues will be resolved when shadcn v5 ships React 19 native
    // components. For now, we relax strict rules on the ui/ directory.
    files: ['src/components/ui/**/*.tsx'],
    rules: {
      '@typescript-eslint/no-deprecated': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
    },
  },
  {
    // Test files use vi.mock() which returns any, and often have conditional
    // logic that TypeScript can statically analyze. Relax strict type-safety
    // rules for test files — runtime behavior is verified by the tests themselves.
    files: ['**/*.test.ts', '**/*.test.tsx'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/require-await': 'off',
    },
  },
];
